apiVersion: v1
kind: Secret
data:
  password: JGFwcjEkYUROZjc5YkIkdWp4L2dzdm1CWC9CM1MzdWhoeTlULg==
  username: aG9sb3NpeA==
metadata:
  labels:
    edgelm.sap.com/product: edgelm
  name: squid
type: Opaque
